### ISSUE TITLE
Problem: Whether the perturbation range is optional？

### ISSUE THREAD

**Issue by nnjnjn** [Verified-Intelligence/auto_LiRPA#33]
Hi, I was wondering if there is an easy way to perturb a part of the input or a part of the model parameters? For example, the upper part of the picture or several parameters in a certain layer?

**Comment by shizhouxing** [comment]
@nnjnjn 

Yes, you may see #30 . You may only add perturbations only on some elements in `x_L` and `x_U`. 

For example: `x_L=torch.tensor([0, 1, 2]); x_U=torch.tensor([0, 1.5, 2])` only has the second element perturbed.
