### ISSUE TITLE
Providing intermediate constraints

### ISSUE THREAD

**Issue by shubhamugare** [Verified-Intelligence/auto_LiRPA#37]
Hi,

How can I provide intermediate constraints to the `compute_bounds` method? 
I see that the `compute_bounds` method takes the map `intermediate_constr` in its signature, but I'm unsure about the exact type of this map. Is it some sort of activation mask?

Thanks

**Comment by huanzhang12** [comment]
The parameter `intermediate_constr` was used in some experimental features and should not be used. It will be removed in a future release.
Could you give us more details on what kind of constraints you want to add?

**Comment by shubhamugare** [comment]
For instance, if I have a subset of ReLUs that I assume are positive (or negative).

**Comment by shizhouxing** [comment]
@shubhamugare You may provide intermediate bounds with the `intermediate_layer_bounds` argument:
https://github.com/Verified-Intelligence/auto_LiRPA/blob/master/auto_LiRPA/bound_general.py#L1129

**Comment by shubhamugare** [comment]
Great! that should work for me. I think I can do `[0, \infty]` for some neurons to make them strictly positive. Thanks @huanzhang12  and @shizhouxing
