### ISSUE TITLE
Loading bounded model as a child

### ISSUE THREAD

**Issue by nurlanov-zh** [Verified-Intelligence/auto_LiRPA#40]
If we have a parent `nn.Module`, which has two children modules: `self.net: nn.Module` and `self.bounded_net(self.net): BoundedModule`, the following issue occurs:
1. When saving a `state_dict` of parent module, we save all 'net' and 'bounded_net' parameters, which are equal to each other (effectively doubling the size of `state_dict`).
2. When we load it from parent module, we can successfully load `state_dict` of 'net' child, but the 'bounded_net' child contains no `_buffers` and no `_parameters`. Additionally, the keys of `bounded_net._modules` have a leading `/` symbol (that does not exists in the saved `state_dict` for 'bounded_net'),  which results in: 
```
RuntimeError: Error(s) in loading state_dict for ParentModule: 
Unexpected key(s) in state_dict: "bounded_net.0.weight", "bounded_net.0.bias"...
``` 

I assume saving both net, and bounded net is not correct. What should one do in this case?

**Comment by nurlanov-zh** [comment]
The same error occurs if we have only `self.bounded_net(net): BoundedModule` as an only child.

**Comment by huanzhang12** [comment]
The library was designed as a wrapper of nn.Module object to allow bound computation, and it is not intended to be serializable. Ideally, you should load and save the original model, not the wrapped model. If you have a use case where the load/save of a BoundedModule object is absolutely necessary, please report to us.

**Comment by nurlanov-zh** [comment]
I see. In my case it is also possible to find a workaround and save/load only the weights of the original model. Thanks for your response!
