### ISSUE TITLE
Exponentially increasing computation time with increasing network size

### ISSUE THREAD

**Issue by nrober1122** [Verified-Intelligence/auto_LiRPA#43]
**Describe the bug**
I have found that depending on the configuration of the `nn.Module` being analyzed, the computation time of `compute_bounds` using the `backward` method increases exponentially with network size, as opposed to quadratically as claimed in various crown papers and demonstrated by analyzing other `nn.Module`s.

**To Reproduce**
1. Minimum example is provided in [this colab ](https://colab.research.google.com/drive/1DdcnZ4lMn465vM0uwj-b1IukXJJiFm5M?usp=sharing)
2. The pytorch state_dict file is attached, which can be unzipped then uploaded into the colab file structure. 
[single_pendulum_small_controller.torch.zip](https://github.com/Verified-Intelligence/auto_LiRPA/files/10975071/single_pendulum_small_controller.torch.zip)
3. To replicate this trend, please open the colab (optionally, save as a copy so you can edit as the above link just provides viewing permission). Unzip & upload the provided .torch model file. Run the first cell to clone & install auto-lirpa. Restart the runtime and auto-lirpa will be fully installed (no need to re-run the first cell again). Run the subsequent cells to define the model class, load the state_dict, and run the test case. The test case is an example where runtime increases exponentially, so will take a little over two minutes to run. Note if you encounter the error `RuntimeError: Unable to cast from non-held to held instance (T& to Holder<T>)`, you should restart the runtime and re-run all cells but the first. This error seems to be specific to colab.

**System configuration:**
 - OS: Ubuntu 20.04 (provided by colab)
 - Python version: Python 3.9.16
 - Pytorch Version: 1.13.1
 - Hardware: google colab
 - Have you tried to reproduce the problem in a cleanly created conda/virtualenv environment using official installation instructions and the latest code on the main branch?: implemented in a new colab file
 

** Screenshot **
![exponential_scale](https://user-images.githubusercontent.com/82716914/225180464-16274284-1faa-47b0-917b-208cde4cfcbc.png)

**Comment by shizhouxing** [comment]
Hi @nrober1122 , for smaller networks, more ReLU neurons tend to be stable (always inactive or active), and the library has been optimized to more quickly handle those neurons. That may explain the trend of computation time you observed.

**Comment by huanzhang12** [comment]
@nrober1122 The complexity should be polynomial when you disable the sparse activation optimization. The sparsity helps the algorithm run even faster, but when there is less/no sparsity on unstable neurons when you enlarge your network, you will notice a super-polynomial slow down compared to the case with sparsity.

@shizhouxing Just in case some people may need this later, can you leave an example that disable all sparse neuron optimizations?

**Comment by shizhouxing** [comment]
The sparse optimization can be disabled setting `bound_opts` when creating the `BoundedModule` (like `BoundedModule(model, nominal_input, bound_opts=...)`, where `bound_opts` can be set as follows:

```
bound_opts = {
    'sparse_intermediate_bounds': False,
    'sparse_conv_intermediate_bounds': False,
    'sparse_intermediate_bounds_with_ibp': False,
    'sparse_features_alpha': False,
    'sparse_spec_alpha': False,
}
```
