### ISSUE TITLE
Issues on examples/vision/simple_verification.py with different parameters

### ISSUE THREAD

**Issue by r11942152** [Verified-Intelligence/auto_LiRPA#54]
Dear auto_LiRPA Team,

Thanks for your work!

Your **simple_verification.py** works perfectly when we run the code
```
python simple_verification.py
```
with the provided checkpoint:
```
# Optionally, load the pretrained weights.
checkpoint = torch.load(
    os.path.join(os.path.dirname(__file__), 'pretrained/mnist_a_adv.pth'),
    map_location=torch.device('cpu'))
model.load_state_dict(checkpoint)
```

However, when we attempt to run the code with our self-trained parameters using your **mnist_model** structure in **simple_verification.py**, we encounter an issue. Specifically, we modify the checkpoint as follows:
```
# Optionally, load the pretrained weights.
checkpoint = torch.load(
    os.path.join(os.path.dirname(__file__), 'pretrained/mnist_a_adv_autre.pth'),
    map_location=torch.device('cpu'))
model.load_state_dict(checkpoint)
```
At this point, the code results in a runtime error:
```
RuntimeError: shape mismatch: value tensor of shape [32, 2, 16, 14, 14] cannot be broadcast to indexing result of shape [32, 2, 3088, 14, 14]
```
We would appreciate it if you could provide guidance or assistance in resolving this issue. 
Additionally, you can download our parameters from
```
wget -O mnist_a_adv_autre.pth https://www.dropbox.com/scl/fi/u91gh37fxilj78z1aso8s/mnist_a_adv_autre.pth?rlkey=bgf4ty740pspt2cyi1c9pewtc&dl=1
```

Thank you for your help.

**Our System configuration:**
 - OS: Ubuntu 18.04.6 LTS
 - Python version: Python 3.8.17
 - Pytorch Version: PyTorch 1.12.1
 - Hardware: NVIDIA GeForce GTX 1080 Ti
 - Have you tried to reproduce the problem in a cleanly created conda/virtualenv environment using official installation instructions and the latest code on the main branch?: Yes

**Comment by KaidiXu** [comment]
I cannot reproduce this error when loading the checkpoint you provided. The outputs are normal.

**Comment by shizhouxing** [comment]
@r11942152 You may disable "sparse alpha" for now by changing the following lines when creating `BoundedModule`:

```
lirpa_model = BoundedModule(
    model, torch.empty_like(image), device=image.device,
    bound_opts={
        'sparse_features_alpha': False,
        'sparse_spec_alpha': False,
    })
```

**Comment by r11942152** [comment]
@shizhouxing It works. Thank you for your assistance!
