### ISSUE TITLE
Can we somehow constrain BoundedModule.compute_bounds() lower bound to not be negative?

### ISSUE THREAD

**Issue by Soothysay** [Verified-Intelligence/auto_LiRPA#59]
Hi, I have been playing around with the library with different datasets and found that BoundedModule.compute_bounds() with options to give both lb and ub always gives negative lb values. Is there any way we can constrain lb to be >0?

**Comment by shizhouxing** [comment]
Hi @Soothysay , if it gives a negative lower bound, it means that the verifier can't certify a better lower bound (or a postive lower bound) at this time. We can't add a hard constraint (lb > 0) if that's the property we want to certify.

To get better bounds, you may consider:
* Trying a stronger verifier. When you are calling `compute_bounds`, did you try `method=CROWN-optimized`? You may also try our complete verifier (https://github.com/Verified-Intelligence/alpha-beta-CROWN) which can further refine the bounds by branch-and-bound at a larger computational cost. 
* Training a better model by certified robust training (e.g., https://github.com/shizhouxing/Fast-Certified-Robust-Training)

**Comment by Soothysay** [comment]
Thanks for the clarification. This helps!
