### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ytsao** [Verified-Intelligence/auto_LiRPA#66]
When I followed the instruction to install auto_LiRPA, I got the error message as following:
"error: torch 2.0.1 is installed but torch==2.2.1 is required by {'torchvision'}"

Therefore, I tried to modify the setup.py file, to specify the torch version as 2.2.1 to install.
And then, run "python setup.py install" again, then it works!

However, when I tried to run the examples which you provided, I got the following error message:
"ImportError: cannot import name '_set_opset_version' from 'torch.onnx.symbolic_helper' (/usr/local/lib/python3.10/dist-packages/torch-2.2.1-py3.10-linux-x86_64.egg/torch/onnx/symbolic_helper.py)"

So, is that a installation bug or something I misunderstand when I installed this package?

Thanks!

**Comment by shizhouxing** [comment]
Hi @ytsao , thanks for reporting this issue! The current version does not support torch 2.2 well, and torch 2.0 is recommended for now (along with the torchvision matching torch 2.0). Mentioned at https://github.com/Verified-Intelligence/auto_LiRPA/blob/master/setup.py#L7. 

But we are planning to release a new version soon which supports torch 2.2.

**Comment by ytsao** [comment]
Hi @shizhouxing , thanks for your swift reply!
Yes, I saw you mentioned in the setup.py file. But when I used this setup.py file to install torch. It is going to search torch 2.0, but the following steps I will get the error message as following picture:
<img width="641" alt="Screenshot 2024-03-14 224335" src="https://github.com/Verified-Intelligence/auto_LiRPA/assets/39461286/e618b6bd-8158-4f8c-839e-b14055783be6">

**Comment by shizhouxing** [comment]
We also need to add a version constraint for torchvision. 

Could you please pre-install pytorch along with a compatible torchvision beforing running `python setup.py install` for now? 
See https://pytorch.org/get-started/previous-versions/#linux-and-windows-10

**Comment by ytsao** [comment]
Hi @shizhouxing , I think I have installed successfully! Thank you for your help!
