### ISSUE TITLE
How is BoundedModule.split_nodes initialized?

### ISSUE THREAD

**Issue by nhamlv-55** [Verified-Intelligence/auto_LiRPA#69]
I am trying to understand this function
https://github.com/Verified-Intelligence/auto_LiRPA/blob/2553832b5a5bbfe643b694458867ebd1dbdece65/auto_LiRPA/beta_crown.py#L80

The code is iterating over self.split_nodes, which is not initialized anywhere. I noticed that because when I run auto-LiRPA on my code, the code crashes and says that `split_nodes` does not exist. The only other places where I can see it is in https://github.com/Verified-Intelligence/auto_LiRPA/blob/2553832b5a5bbfe643b694458867ebd1dbdece65/auto_LiRPA/beta_crown.py#L45 , but the function `get_split_nodes()` is not called anywhere.

Could someone please explain how it works?

**Comment by shizhouxing** [comment]
Hi @nhamlv-55 , it is supposed to be used by [alpha-beta-CROWN](https://github.com/Verified-Intelligence/alpha-beta-CROWN)
