### ISSUE TITLE
 error in setup repo on wrong graphic char 0x8f (PLAY)  in README

### ISSUE THREAD

**Issue by bardout** [Verified-Intelligence/auto_LiRPA#82]
**Describe the bug**
remove graphic char (PLAY) in README to allow setup the repo under Windows 11, python 3.11.7 

**To Reproduce**
```
git clone https://github.com/Verified-Intelligence/auto_LiRPA
cd auto_LiRPA
pip install .

error setup.py, line 29, in read_text "pathlib.py", line 1059, 
          long_description = (this_directory / 'README.md').read_text()
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 4934
(this is the icon PLAY video inserted in this file)

```
**correction**:
 removal of special graphic char (PLAY) in README 
After removal locally, at least this step works fine.

**System configuration:**
 - OS: Windows 11
 - Python 3.11.7 
 - Pytorch 2.2 (as handled by setup)
 - Hardware: Processeur	13th Gen Intel(R) Core(TM) i7-13850HX, 2100 MHz, 20 cœur(s), 28 processeur(s) logique(s)

**Additional context**
NA

**Comment by shizhouxing** [comment]
Hi @bardout, I think the issue is that your python on windows is not using UTF-8 encoding:
https://docs.python.org/3/using/windows.html#utf-8-mode
