### ISSUE TITLE
node has an unsupported operation: onnx::SequenceConstruct, onnx::SequenceAt 

### ISSUE THREAD

**Issue by paullutkus** [Verified-Intelligence/auto_LiRPA#89]
I am trying to perform verification on a Module whose forward pass contains indexing and concatenation by hstack. I am encountering the following error that upon running BoundedModule(\<Feedback dynamics object\>, ...):
```
fdyn_1 = FeedbackDynamics(fdyn, lqr, component=0)
lirpa_fdyn_1 = BoundedModule(fdyn_1, torch.empty_like(z))
```
```
ERROR   13:49:39     The node has an unsupported operation: Node(name='/46', ori_name=None, inputs=['/0', '/45'], attr={}, op='onnx::SequenceConstruct', param=OrderedDict({'/0': None}), input_index=None, bound_node=None, output_index=0, perturbation=None)
ERROR    13:49:39     The node has an unsupported operation: Node(name='/48', ori_name=None, inputs=['/46', '/47'], attr={}, op='onnx::SequenceAt', param=OrderedDict(), input_index=None, bound_node=None, output_index=0, perturbation=None)
ERROR    13:49:39     The node has an unsupported operation: Node(name='/50', ori_name=None, inputs=['/49'], attr={}, op='onnx::Size', param=OrderedDict(), input_index=None, bound_node=None, output_index=0, perturbation=None)
ERROR    13:49:39     The node has an unsupported operation: Node(name='/53', ori_name=None, inputs=['/52'], attr={}, op='onnx::If', param=OrderedDict(), input_index=None, bound_node=None, output_index=0, perturbation=None)
ERROR    13:49:40     Unsupported operations:
ERROR    13:49:40     Name: onnx::SequenceConstruct, Attr: {}
ERROR    13:49:40     Name: onnx::SequenceAt, Attr: {}
ERROR    13:49:40     Name: onnx::Size, Attr: {} # IGNORE
ERROR    13:49:40     Name: onnx::If, Attr: {} # IGNORE
```

The FeedbackDynamics class is defined as follows:

```
class FeedbackDynamics(nn.Module):
    def __init__(self, dynamics, controller, component=0):
        super().__init__()
        self.dynamics = dynamics
        self.controller = controller
        self.component = component`
        
    def forward(self, x):
        x.requires_grad = False
        return self.dynamics( torch.hstack((x, self.controller(x))) )[self.component]
```

Is it possible that this error is being caused by the use of torch.hstack and indexing the 'self.component' entry of the output?
There are other unsupported operations present (If and Size), but I am particularly interested in the SequenceConstruct and SequenceAt. If more information is required, please let me know.

**Comment by shizhouxing** [comment]
Hi @paullutkus, it looks like `hstack` is not supported yet. Would it be possible for you to use concat instead? Or maybe modify `self.dynamics` to take two arguments (x and controller's output) without `hstack`?

We have an example here: https://github.com/Verified-Intelligence/Lyapunov_Stable_NN_Controllers/blob/main/neural_lyapunov_training/lyapunov.py#L341  from paper https://arxiv.org/pdf/2404.07956.

**Comment by paullutkus** [comment]
Thanks for the suggestions! I'll try these out and then get back to you.

**Comment by paullutkus** [comment]
This fixed the error. Thank you for your help!
